name: radio_fi
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  get_it: ^4.0.4
  flutter_radio_player: ^1.0.7
  path_provider: ^1.6.18
  package_info: ^2.0.2
  country_codes: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^1.3.0

flutter:
  uses-material-design: true
  generate: true