name: radio_fi
description: A new Flutter project.
version: 0.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  http: ^1.6.0
  get_it: ^9.2.1
  path_provider: ^2.1.6
  package_info_plus: ^10.2.1
  country_codes: ^3.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.4.2
  just_audio: ^0.10.6
  just_audio_windows: ^0.2.3
  msix: ^3.18.0
  connectivity_plus: ^7.3.1
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: Radio Fi App
  publisher_display_name: Radio Fi App
  identity_name: radio.fi.flutterapp
  msix_version: 1.0.0.0
  logo_path: C:\src\personal\radio_fi_app\windows\runner\resources\app_icon.ico
  capabilities: internetClient