name: radio_fi
description: A new Flutter project.
version: 0.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  get_it: ^7.2.0
  path_provider: ^2.0.9
  package_info: ^2.0.2
  country_codes: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.0.2+1
  just_audio: ^0.9.40
  just_audio_windows: ^0.1.0
  msix: ^3.6.2
  connectivity_plus: ^2.3.6

flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: Radio Fi App
  publisher_display_name: Radio Fi App
  identity_name: radio.fi.flutterapp
  msix_version: 1.0.0.0
  logo_path: C:\src\personal\radio_fi_app\windows\runner\resources\app_icon.ico
  capabilities: internetClient