name: radio_fi
description: A new Flutter project.
version: 2.0.1+3

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  get_it: ^4.0.4
  flutter_radio_player: ^1.0.7
  path_provider: ^1.6.18

flutter:
  uses-material-design: true