name: radio_fi
description: A new Flutter project.
version: 0.0.2+2

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  get_it: ^7.2.0
  flutter_radio_player: ^1.1.0
  path_provider: ^2.0.9
  package_info: ^2.0.2
  country_codes: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.2+1
  just_audio: ^0.9.27
  just_audio_windows: ^0.1.0

flutter:
  uses-material-design: true
  generate: true